### ISSUE TITLE
Dataset structure for EVSegNet

### ISSUE THREAD

**Issue by ercanburak** [prgumd/EVDodgeNet#5]
Hello. While trying to understand the EVSegNet code you provided, I have seen that the RunEVSegNet.py and TrainEVSegNet.py scripts have a function named "SetupAll" where certain files named "DirNames.txt" and "Train.txt" are trying to be read, like the following:

https://github.com/prgumd/EVDodgeNet/blob/0b6f6a0fc781203d3bc395c5305ff7c7ffc7535e/code/EVSegNet/RunEVSegNet.py#L60-L62

Checking the dataset from https://drive.google.com/open?id=1pJSVXtRlTU4_b-I8oakoZtl1ChcG0OiQ and also checking the dataset structure desciption in https://github.com/prgumd/EVDodgeNet/wiki/Access-Data-Set-Using-ROS-Python, I could not find any file named "DirNames.txt" or "Train.txt". What am I missing here, can you guide me on this?

**Comment by celynw** [comment]
Any luck?

I've found that `Misc/DataParse.py` for each network is supposed to generate `DirNames.txt`, but I'm still confused.
It looks like it's expecting events and labels in `png` format.

https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DeblurNetUnsup/Misc/DataParse.py#L26

According to the instructions, I can download the dataset, which has events as a space-delimited `.txt` file or as messages in a rosbag, and the provided scripts only extracts images.

**Comment by NitinJSanket** [comment]
@ercanburak Please use this function to generate `DirNames.txt` and related files. https://github.com/prgumd/EVDodgeNet/blob/master/code/DataProcessingUtils/DataParseUnstack.py
Alternatively, you can create `DirNames.txt` yourself by creating a `.txt` file with names of all images (one name per line). Do let me know if you face any issues

**Comment by celynw** [comment]
Thanks very much for the response.

But what about _events_?
The script you pointed to seems to expect events in `.png` format.
https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/DataParseUnstack.py#L25
How can I get these?

- I can download events as `.txt` files (dataset structure [here](https://github.com/prgumd/EVDodgeNet/wiki/Access-Data-Set-Using-ROS-Python))
- I can download the ROS bags, but [`extract_davis_bag_files.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/extract_davis_bag_files.py) and [`bag_to_images.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/simulator/rpg_davis_simulator/scripts/bag_to_images.py) extract only the RGB camera feed as `.png` images.
There don't seem to be anoy other scripts in the repository for extracting from ROS bags,

Have I misunderstood?

It seems like there is functionality to generate the event images in [`event.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/EventFrameGeneration/event.py) but it doesn't seem to be referenced anywhere.
Is this correct?

Either way, I think the wiki could do with updating/correcting.

**Comment by celynw** [comment]
I think I finally have something.

I first had to obtain `.txt` event files along with the extracted RGB images with [`DataProcessingUtils/extract_davis_bag_files.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/extract_davis_bag_files.py).

Then to extract the event images I had to run [`DataProcessingUtils/EventFrameGeneration/main.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/EventFrameGeneration/main.py), and also edit it to call `generate_evframe` rather than `generate_evtime` (this looks like development test code...).
I also had to edit [`DataProcessingUtils/EventFrameGeneration/event.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/EventFrameGeneration/event.py) to read `events.txt` instead of `images.txt`, and to remove the `cv2.imshow`.
This is _extremely_ slow. Do you have these preprocessed files available to download?
I think this generates the event images needed for the next step, generating `DirNames.txt` with [`DataParseUnstack.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/DataParseUnstack.py).
I can run these through `TrainEVSegNet.py` (although there is an image size mismatch).

I'd appreciate your help on this.
Is this a pre-release? Although it looks like a lot of effort went into developing and releasing the code and dataset, lots of things seem quite broken.

**Comment by NitinJSanket** [comment]
> I think I finally have something.
> 
> I first had to obtain `.txt` event files along with the extracted RGB images with [`DataProcessingUtils/extract_davis_bag_files.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/extract_davis_bag_files.py).
> 
> Then to extract the event images I had to run [`DataProcessingUtils/EventFrameGeneration/main.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/EventFrameGeneration/main.py), and also edit it to call `generate_evframe` rather than `generate_evtime` (this looks like development test code...).
> I also had to edit [`DataProcessingUtils/EventFrameGeneration/event.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/EventFrameGeneration/event.py) to read `events.txt` instead of `images.txt`, and to remove the `cv2.imshow`.
> This is _extremely_ slow. Do you have these preprocessed files available to download?
> I think this generates the event images needed for the next step, generating `DirNames.txt` with [`DataParseUnstack.py`](https://github.com/prgumd/EVDodgeNet/blob/c78942ac454ed05ceb6063088458d47674a8ba9b/code/DataProcessingUtils/DataParseUnstack.py).
> I can run these through `TrainEVSegNet.py` (although there is an image size mismatch).
> 
> I'd appreciate your help on this.
> Is this a pre-release? Although it looks like a lot of effort went into developing and releasing the code and dataset, lots of things seem quite broken.

We'll recheck everything after March 1 and fix any issues.
